### ISSUE TITLE
Word Search: Looping around wrong letters

### ISSUE THREAD

**Issue by AndrewRigg** [AndrewRigg/Crossword#104]
When a snake word has two or more possibilities, (e.g. two identical letters connected at the end of the word) and the user chooses the wrong one (the arbitrarily assigned one by the algorithm) the algorithm will think the answer is correct as the letters are correct but will loop around the original letters which looks a bit funny.

Different options are:

- We leave it in as a deliberate feature

- We loop around the correctly spelled selection the user chose even if it's not the original word

- We don't loop it unless they guess the original selection even if ambiguous, so depends on luck by the user

- We ensure no ambiguous words are entered into the wordsearch 

For the latter, an easy temporary solution would be to make sure the last letter is the only one around the second last letter and likewise for the first letter.

**Comment by Golpette** [comment]
I say leave it in as a deliberate feature. Makes most sense and is the easiest.

The second option is just unnecessary work in my opinion.

The third option isn't fair and would just irritate users.

The last option would be way too much work to implement (we'd need an actual wordsearch solver which I don't want to write) and would slow down the generation time
