### ISSUE TITLE
Wordseach: add highlighting method

### ISSUE THREAD

**Issue by Golpette** [AndrewRigg/Crossword#18]
Add method for users to highlighting the words (and also how to display the solutions).
Before implementing something, let's discuss here the best way we think we can do this, since there are a few different options.

**Comment by AndrewRigg** [comment]
Closing this as the requirements didn't make sense.  If a user selects a letter, how are we to know which word they are choosing?!  It is different from the crossword in this regard.  Highlighting of the solutions has already been implemented and looping of correctly selected words has also been implemented.
