### ISSUE TITLE
Document code properly

### ISSUE THREAD

**Issue by Golpette** [AndrewRigg/Crossword#19]
Some classes have zero comments. Write proper code documentation: comments, method explanations etc. Very important if we're collaborating and I want to edit/play with what you've done!

**Comment by camieac** [comment]
A README.md file would be nice :) Just to give curious onlookers like me an idea of what the project is about. Example: https://gist.github.com/jxson/1784669

**Comment by AndrewRigg** [comment]
The readme has been there the whole time I believe.  This issue is largely irrelevant as the code has changed so much and we have been adding more comments.  (Getting better at adding them) and this issue will be superseded by the issue to properly use javadocs.
