### ISSUE TITLE
Organise project setup

### ISSUE THREAD

**Issue by AndrewRigg** [AndrewRigg/Crossword#31]
Create proper folders and hierarchies of files in the project so that it is easier to use when more complex and expanded.

More precisely create sub packages in the source folder e.g.
1. Crossword - All crossword related code
2. Wordsearch - All wordsearch related code
3. Sudoku - All sudoku related code
4. GUIs - All GUI classes and related code
5. Resources
6. Algorithms

(Something like this - but think about the most logical and efficient structure)

**Comment by Golpette** [comment]
I know I said yesterday I can't be bothered thinking about this but maybe it is a good idea... there are rules and procedures to software development and one of the most important things I'll take from this exercise would be to learn to use them properly!

**Comment by AndrewRigg** [comment]
Is this done well enough?  This may well be a continuous issue but I will close it for now as the main thing has been done.
