### ISSUE TITLE
Missing .txt files

### ISSUE THREAD

**Issue by camieac** [AndrewRigg/Crossword#37]
I tried to get this thing going and encountered the following error:

```
java.io.FileNotFoundException: words_cambridge.txt (No such file or directory)
```

My guess is that you have this file, and the repository doesn't?

**Comment by Golpette** [comment]
Yep, it's in the repo and should be in the correct directory. Are you using eclipse?

**Comment by camieac** [comment]
Found it! I somehow didn't notice the file earlier. Yeah I was in the wrong directory, and not using Eclipse :) I'll try again tomorrow. Cheers
