### ISSUE TITLE
Wordsearch: new fitting class

### ISSUE THREAD

**Issue by Golpette** [AndrewRigg/Crossword#38]
Separate classes for fitting procedures in wordsearches and crosswords. 

The original crossword procedure is designed to avoid things like adjacent words (since then we'd have multiple adjacent white squares that did not form a word) and is thus overly restrictive: in a wordsearch we don't care if 2 words are side by side.

This will make it easier to specifically modify for diagonal/backwards words in wordsearches.

Implication:  highlighting all words in same colour in the solution will make it tricky to distinguish words. Either need to choose different colours for different words or use something like loops / lines to highlight them. 

We can set a number of words to fit depending on size of grid.

**Comment by AndrewRigg** [comment]
Great idea, this means we will be able to use smaller word lists as well and so can do categories of things with more success.  In regards to highlighting, I will attempt to use loops like discussed in other issue.

**Comment by Golpette** [comment]
I don't think the size of word lists was ever a problem for wrodsearches though? I've started wokring on this in the diagonalWords branch - shouldn't be hard just need to find a spare hour or so to rearrange everything properly.

Yup, maybe looping the words would look nicest (but also trickiest t implement!). Maybe we can discuss this further just to be sure about what you'll be using to do this (for example, do you care if I start altering the Entry ArrayList / actual Object parameters etc.)

**Comment by AndrewRigg** [comment]
Cool.  No that's fine, go for it man.  I have just started making images that can be used for the loops.  Which colour (if any) would you like to have them?  (Ie the colour that highlighted words will be shown in.)

Is it also ok if I rehash the drawing wordsearch method as it is not very good.  I was going to redo the way we put the letters in and get the clicks working.  (And put clear comments in)

Also do we want to be able to use arrows on the wordsearch as well (even though they are not textfields?)  or is it best to just have clicks for this?

**Comment by Golpette** [comment]
Lol, just choose a colour and if we change our mind later... we can change the colour! No doubt the whole look is going to change anyways.

I don't know how you'd use the arrow keys in a wordsearch? You mean to highlight letters, then click enter or something? Clicking and dragging would feel more intuitive

**Comment by AndrewRigg** [comment]
I've just left it the blue colour from before.  
It's just gonna be annoying to change all images once their done.  (There will be 16 in total.)  Although I think they may be too wide at present so may have to redo them anyway.  It will be tricky because when doing diagonals we will need to display a corner bit of the loop in adjacent cells to the word.

Yes I agree, let's not bother implementing anything with the keyboard for wordsearch.

**Comment by Golpette** [comment]
Added up/back/diagonal and backwards-diagonal words. 
Allow words to be adjacent to others.
Pushed to master
