### ISSUE TITLE
Wordsearch: Randomised letters won't change colour

### ISSUE THREAD

**Issue by AndrewRigg** [AndrewRigg/Crossword#39]
There is seemingly a bug where the letters which are generated between the words will not change background colour when the mouse is clicked.  I have no idea why.  (Probably something obvious and stupid I've done)
This is in DrawWordSearch class.

Good luck!

**Comment by Golpette** [comment]
Also:  cannot highlight letters until "show solution" has been clicked.

**Comment by AndrewRigg** [comment]
I think this was to do with opacity (background to show requires opacity = true), which was awkward when working with jlayered panes which need to be transparent, but easy fix is to just change the opacity of cells as and when required. 

These have both been fixed (and are somewhat irrelevant now anyway).
