### ISSUE TITLE
Wordsearch: difficulty selection

### ISSUE THREAD

**Issue by Golpette** [AndrewRigg/Crossword#40]
Could add various difficulty options: "Easy" might only include down and across words, "medium" diagonal and back, "hard" backwards-diagonal too. 

Maybe number of words too?

Ideas?

**Comment by AndrewRigg** [comment]
Good idea about difficulties.  Wouldn't it be more logical to just do:

Easy: Across and Down
Medium: Add diagonals
Hard: Backwards for all directions
- Expert: Words can snake around!  (Not sure if this is a joke)

**Comment by Golpette** [comment]
"Wordsnakes"... I could do it and see how it looks.

But yeh... we're spending time creating 3 puzzles that already exist. It would better to create an entirely new puzzle. One that takes the world by storm...

**Comment by AndrewRigg** [comment]
Exactly!  Word snakes sounds good.  Maybe we'll have them moving as well, like a wordsearch/tetris hybrid!

**Comment by AndrewRigg** [comment]
Completed this except for the word snakes.  Will open that as a new issue.
