### ISSUE TITLE
Word Search: Word Snakes

### ISSUE THREAD

**Issue by AndrewRigg** [AndrewRigg/Crossword#47]
Create an 'expert' option for the word search which allows words to snake around in any direction.
(Had this mostly implemented but it contained a few bugs.)

**Comment by Golpette** [comment]
Not merged but fitting procedure works; see branch "snakey_steve".  
Snakes in up-down-left-right directions.
Future idea might be to favour the previous direction by some factor so that snakes are more likely to "travel" than curl up into squares.
