### ISSUE TITLE
Wordsearch: Disallow palindromic words

### ISSUE THREAD

**Issue by AndrewRigg** [AndrewRigg/Crossword#51]
Palindromic words could be problematic, ie user will not get it correct unless they choose the correct direction which was created randomly, either should handle this or disallow palindromic words.

**Comment by Golpette** [comment]
Do not be lazy

**Comment by AndrewRigg** [comment]
Have included a method in Entry to say whether the word is palindromic or not.

**Comment by AndrewRigg** [comment]
Have allowed the palindromic words to be selected from either end.
