### ISSUE TITLE
Scrolling when CTRL not pressed

### ISSUE THREAD

**Issue by AndrewRigg** [AndrewRigg/Crossword#62]
Need to find a way to allow scrolling to occur when in focus, when CTRL is not pressed.  (Implementing CTRL + scroll for zooming seems to have impaired the automatic scrolling).

**Comment by Golpette** [comment]
I think scrolling is fixed in both crossword and wordsearch now?

1 bug I couldn't figure though, is that the scroll bar only attaches to the wordsearch grid - the clues just get dropped off the end.
