### ISSUE TITLE
Allow crossword to still display highlighted words on zooming

### ISSUE THREAD

**Issue by AndrewRigg** [AndrewRigg/Crossword#65]
Zooming currently removes highlighted squares.  Need to save them to temporary array and then redraw them when zooming used.

**Comment by AndrewRigg** [comment]
There is now just a subtle bug, the zooming works fine and the words highlight fine, but when zooming, the highlighted word jumps to the most recently clicked word, i.e. it seems that the clicked word trumps the currently hovered word.

**Comment by Golpette** [comment]
I fixed this, but introduced a smaller bug where the highlighted grid loses its focus
