### ISSUE TITLE
Wordsearch: Solution shows separate words

### ISSUE THREAD

**Issue by AndrewRigg** [AndrewRigg/Crossword#71]
Currently clicking solution on wordsearch shows a big confusing green blob and there is no way of telling solution words apart.  Need some way of separating the words when solution is called such as drawing coloured loops around them.

--Possibly want to alter the solution method to only show one word or similar?

**Comment by Golpette** [comment]
Easiest thing to do for now is just show the solution as in the actual puzzle no? (At least this would be useful for debugging) and we can get rid of it later.

Or if  you wanted you could add a couple extra buttons such as "Gimme a hint" which maybe flashes one letter in in the word in red for a split second... (maybe just flashes one letter in any word that hasn't been found?) and a "Just show me already!" button which is like giving up and just loops a word (which would involve being able to select a word from the list)

**Comment by AndrewRigg** [comment]
Have already sorted the title of the issue.
Working on separate things for 'hint' and 'clue', to show one word or hint within one word.

**Comment by AndrewRigg** [comment]
Fixed this a while ago.
