### ISSUE TITLE
Improve usability of crossword textfields.

### ISSUE THREAD

**Issue by AndrewRigg** [AndrewRigg/Crossword#9]
Allow the user to select other boxes easily by using the arrow keys, or when typing a letter the cursor should move to the next available box.
When deleting, the text should be removed from subsequent boxes.  If there is no word across but a word down, the cursor should jump to the next textfield down.

**Comment by AndrewRigg** [comment]
Have made arrow keys work fine, made basic functionality for backspace and adding letters but there are several issues with the inputs.  Require decision on how to use in regard to prioritisation of textfields.

**Comment by AndrewRigg** [comment]
The backspace now jumps back over letters that are in the grid or through the empty squares in rows otherwise.

**Comment by Golpette** [comment]
Closing this since it's a bit vague and many of these issues are fixed. Start new issues for each specific problem
